### ISSUE TITLE
OSGi compatible?

### ISSUE THREAD

**Issue by alexweirig** [fo0/AdvancedTokenField#1]
Hello,

could you please make the add-on OSGi compatible, generating a complete MANIFEST.MF with the complete import-packages and export-packages.

This would make it easier to use the add-on in an OSGi environment (Liferay, Karaf ...).

Thanks,

Alex

**Comment by fo0** [comment]
Hi Alex,

thats a good idea. Im going to use the implementation guide on vaadin i'v found:
https://vaadin.com/blog/osgifying-your-add-ons

**Comment by fo0** [comment]
This is my first project where I integrated this OSGi support.
Could you maybe take a look or give it a try. Please tell me if it works not not.

**Comment by alexweirig** [comment]
Hi,

I dont't like using maven so I'm not the pom specialist. In the linked MANIFEST.MF file, the Import-Packages and Export-Packages statements are missing.
I changed the pom.xml and now the result looks better:
1) you need to change the packaging from jar to bundle
<packaging>bundle</packaging>
2) you need to specify which package needs to be exported. My best guess was that
com.fo0.advancedtokenfield.main.* would be enough but you know your add-on better than I do so maybe other packages also need to be exported.
In OSGi, if your bundle doesn't do an explicit export of a package, that package and thus the classes inside the package will not be visible by other classes, e.g. if somebody using your add-on needs to have access to the listeners or events, you need to export those packages as well.

I can't test the add-on today maybe tomorrow I'll be able to deploy it into a karaf and try to use it with a Vaadin OSGi application.

Regards,

Alex

**Comment by fo0** [comment]
could you maybe provide me your pom changes that I can take a look ?
But anyway im going to do some tests and keep looking on the Export Statements inside the MANIFEST.MF

**Comment by alexweirig** [comment]
Hi,

not sure if it was the best thing to do but I tried to create a pull request with the changes I made to the pom.xml ...

HTH

**Comment by fo0** [comment]
I already did this changes. Im going to validate the output and update the version to: 0.0.62

**Comment by fo0** [comment]
Published on Version: 0.0.63
Please check and give me feedback

**Comment by fo0** [comment]
looks like its fixed, no more response.
