### ISSUE TITLE
ComboBox does not clear after insert new Token

### ISSUE THREAD

**Issue by fo0** [fo0/AdvancedTokenField#3]
The ComboBox Value is not cleared after adding a _new_ Token which is not already known and inserted before.
Currently I did some tests but nothing helped me to clear the input in a good.

Would be nice if anyone has an idea to fix these bug.

**Comment by urkl** [comment]
This is really strange. If I add addTokenAddNewItemListener  and `advancedTokenField.getInputField().clear()`   in it, it doesn't change nothing. BUT in debug mode with breakpoint on `advancedTokenField.getInputField().clear();` it stays cleared. Strange.

**Comment by fo0** [comment]
yes, I still couldn't fix this bug, still confusing

**Comment by fo0** [comment]
still not found a good working solution ❌

**Comment by fo0** [comment]
I think it'll replace it with the searchfield addon soon
