### ISSUE TITLE
Vertical layout

### ISSUE THREAD

**Issue by alexxtaurus** [fo0/AdvancedTokenField#4]
Does addon allow align tokens vertically? I'm using forms and vertical layout more relative to this. Also can you object to be used with vaading bindings? Like usual combobox?

**Comment by fo0** [comment]
@vertical request: interesting idea, could you give me a draft, that i can exactly see what u mean?

@binder: im going to impement this, but it could take a while ~2weeks. Maybe you could do a pull request if its important for you

**Comment by alexxtaurus** [comment]
1) it's very easy: exh time i'm add new token, it will be added under combobox, the next token will be added under/up the last one and so on.
2) better use "set" as colleaction. I'm afraid what i don't have much expirience to do such modifications. 

You can search vaadin directory for "TokenField". And see demo how it looks like. i'm using it, but it can be used with 8 version with v7 vaadin packages. I've tryed to migrade it to 8 myself - but no luck.

**Comment by fo0** [comment]
> it's very easy: exh time i'm add new token, it will be added under combobox, the next token will be added under/up the last one and so on.

If I understood you correct, you mean that you want to display the inserted tokens below the tokenfield-combobox, and in a verticallayout + each token per line, correct?

> better use "set" as colleaction. I'm afraid what i don't have much expirience to do such modifications.

I cannot use a Set, because you want to add the same token more then once. The Token-ID is the value itself.

**Comment by alexxtaurus** [comment]
1) here the link with example: https://imgur.com/emKQAYh
2) in case token id's will be kept as value: you cannot use it with binding: i'm use database, i have token field mapped to java class, i want to bind table with string values to the token field.

**Comment by fo0** [comment]
Alright, im going to implement this at the weekend

Am 28.11.2017 13:55 schrieb alexxtaurus <notifications@github.com>:

  1.  here the link with example: https://imgur.com/emKQAYh
  2.  in case token id's will be kept as value: you cannot use it with binding: i'm use database, i have token field mapped to java class, i want to bind table with string values to the token field.

**Comment by fo0** [comment]
hi alex, got some problems with the api for bindings. But im still keep and eye on it, sorry for the delay. The custom layout options i.e. vert layout, will be on the same commit

**Comment by alexxtaurus** [comment]
Cool thanks. It will allow me remove legacy vaadin 7 libs. ps: You can look at vaadin 8.2 it has released already and have improved binding.

**Comment by alexxtaurus** [comment]
Any progress with binding and vertical layout?

**Comment by fo0** [comment]
Hey,

with binding still problems, dont know on what bean to bind. What could be useful ? Bind the Set<Token> or List<String> (token.value) ? Im still not sure what could be a good way...

The Layout gets added on next updates

**Comment by alexxtaurus** [comment]
For my inderstanding and expirience of my colleagues which use tokens at gui: 80% of people want to have set interface and have auto control for unicality of items, so all items will be unic. 20% want to have list interface and doesnt case of unicality. I'm prefer set.

**Comment by fo0** [comment]
So Set<Token> could be a good way of the hasvalue interface return type ? alright, so let me try to finish it this weekend :)

**Comment by alexxtaurus** [comment]
Yes, please use set. Will wait for update. And will do tests

**Comment by LorenzBuehmann** [comment]
Why are you not using the generic type `Collection<T>` as parameter? Indeed, some people might be interested in having a list as backend.

**Comment by alexxtaurus** [comment]
It can be a good idea. And can be a good try. I just provided statistic what i'm have

**Comment by fo0** [comment]
sounds good

**Comment by fo0** [comment]
i'v got many problems with implementing the HasValue interface ... at least im stuck in adding the valuechangelistener to the field... maybe any idea?

```
@Override
	public Registration addValueChangeListener(ValueChangeListener<Collection<Token>> listener) {
		// ??? cannot bind it to inputfield (combobox) or layout (csslayout) ...
		// !!!
	}
```

**Comment by LorenzBuehmann** [comment]
``` Java
@Override
public Registration addValueChangeListener(ValueChangeListener<Collection<Token>> listener) {
   return this.addListener(ValueChangeEvent.class, listener, ValueChangeListener.VALUE_CHANGE_METHOD);
}
```

**Comment by alexxtaurus** [comment]
Hey, any progress yet?

**Comment by fo0** [comment]
i am pretty sorry about the long delay and work, but i am lazy about vaadin projects, but i keep going to work on it

**Comment by fo0** [comment]
dunno but the binder integration breaks my entire component

**Comment by alexxtaurus** [comment]
But about vertical layout? Hoe to configure it?

**Comment by fo0** [comment]
basically its a csslayout, just try to set another style like  "v-horizontallayout"

**Comment by alexxtaurus** [comment]
I will fork this addon and will do required modifications. I've done most of modifications today. The reason, to add binding and layout type choose support. For thise cases main cllass should not extend csslayout but customfield. Class should have ability to chosse required layout. Also it's not removing tokens from combobox just from layout, this will be fixed. Also it depends on drag and drop layout addon. But this addon required to have vaadin-compatible libs at dependency.This is not my case. Will wait  for new addon version (ddl)

**Comment by fo0** [comment]
just do a pull request this is why its open source ...

**Comment by alexxtaurus** [comment]
i have different understanding how tokenfield should work. Starting from i dont understand why use combobox not just text field... also adding binding to component require to do core chnages and it will be new component deffer from your initial one. But it will cover all my needs. But i don't know your needs. You can look at my modifyed code and take parts what you need.

**Comment by fo0** [comment]
yeah i think thats true... Interested on your modifications. I'll keep an eye on it, or maybe you could give me a notification :-)
