### ISSUE TITLE
Usage of scss instead of css and integration to vaadin's addons.scss

### ISSUE THREAD

**Issue by kolmanpav** [fo0/AdvancedTokenField#6]
Hello,
  is it possible to update style sheets to use scss instead of css? It will improve usability - usage of variables etc. 

The second thing is to integrate style sheets into MANIFEST like this:
Vaadin-Stylesheets: VAADIN/addons/advancedTokenField/XXXX.scss 

This will automatically integrate style sheets of your addon to addons.scss file and improve usability and modification of your stylesheets in application 

Best regards,
Pavel

**Comment by fo0** [comment]
thanks for the feedback. I'v got currently not the time to make these changes from css to scss.
What about a pull request from your side?

The second point is not that problem, would it help you if I'll add the following line to MANIFEST.MF?
```
Vaadin-Stylesheets: VAADIN/addons/advancedTokenField/styles.css
```

**Comment by fo0** [comment]
closed because no response from the author
